services:
  geocoder:
    image: ${DOCKER_REGISTRY-}geocoder
    build:
      context: app
      dockerfile: Dockerfile
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

      